# /netlify.toml

[build]
  publish = "dist"
  # Pas aan als je een bundler gebruikt. Voor pure SPA zonder bundler kan dit leeg blijven.

[functions]
  node_bundler = "esbuild"
  included_files = []

# ─────────────────────────────
# SPA fallback
# ─────────────────────────────
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ─────────────────────────────
# Security headers (basis)
# ─────────────────────────────
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Content-Security-Policy
# (Geïnspireerd op jouw eerdere test: laat connect-src 'self' https: toe voor functions, plus data: voor beacons)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-src 'self' https://app.netlify.com; frame-ancestors 'self' https://app.netlify.com; img-src 'self' https: data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https: data:;"

# ─────────────────────────────
# Cache-control (voorbeeld)
# ─────────────────────────────
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ─────────────────────────────
# CORS voor telemetry function
# ─────────────────────────────
[[headers]]
  for = "/.netlify/functions/telemetry"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-RR-Client"
